### ISSUE TITLE
Any idea on a klipper compatible screen that would be plug and play with this?

### ISSUE THREAD

**Issue by cfontes** [9R/kp3sExpander#1]
Hey this is very cool, I am about to install Klipper on mine and the TFT will be useless so this is nice for a Klipper Screen instalation.

What have you used yours to?

**Comment by 9R** [comment]
I use a ssd1306. You just have to make sure to get one with SPI interface, some are sold that only support i2c.

Please use my [klipper example config](https://github.com/9R/Klipper_KP3S/blob/main/display.cfg) as reference for how to connect an ssd1306.

Any other display with SPI interface from the official klipper documentation should also work
